const fs = require("fs");
const path = require("path");

const reportPath = "target/spring-sentinel-reports/report.json";

if (!fs.existsSync(reportPath)) {
    console.error("SpringSentinel report not found.");
    process.exit(1);
}

const report = JSON.parse(fs.readFileSync(reportPath, "utf8"));

const summary = report.summary;

const severityEmoji = {
    critical: "🔴",
    high: "🟠",
    warning: "🟡"
};

const issues = report.issues;

// Raggruppa per motivo (reason)
const grouped = {};

for (const issue of issues) {
    const key = issue.reason;

    if (!grouped[key]) {
        grouped[key] = {
            severity: issue.priority,
            reason: issue.reason,
            file: issue.file,
            line: issue.line,
            count: 0
        };
    }

    grouped[key].count++;
}

// Ordina
const severityOrder = {
    critical: 3,
    high: 2,
    warning: 1
};

const topFindings = Object.values(grouped)
    .sort((a, b) => {

        const sa = severityOrder[a.severity] || 0;
        const sb = severityOrder[b.severity] || 0;

        if (sa !== sb)
            return sb - sa;

        return b.count - a.count;

    })
    .slice(0, 10);

let md = "";

md += "# 🛡 SpringSentinel Report\n\n";

md += "## Summary\n\n";

md += "| Severity | Count |\n";
md += "|----------|------:|\n";
md += `| 🔴 Critical | ${summary.critical} |\n`;
md += `| 🟠 High | ${summary.high} |\n`;
md += `| 🟡 Warning | ${summary.warning} |\n\n`;

md += `**${report.totalIssues} findings detected**\n\n`;

md += "## Categories\n\n";

md += "| Category | Count |\n";
md += "|----------|------:|\n";

const categories = [
    ["Security", summary.security],
    ["Database", summary.database],
    ["Architecture", summary.architecture],
    ["Performance", summary.performance],
    ["REST Design", summary.restDesign],
    ["Best Practice", summary.bestPractice],
    ["Resilience", summary.resilience]
];

for (const [name, value] of categories) {
    if (value > 0)
        md += `| ${name} | ${value} |\n`;
}

md += "\n";

md += "## Top Findings\n\n";

md += "| Severity | Rule | Occurrences | Example |\n";
md += "|----------|------|------------:|---------|\n";

for (const finding of topFindings) {

    const file = path.basename(finding.file);

    md += `| ${severityEmoji[finding.severity]} | ${finding.reason} | ${finding.count} | ${file}:${finding.line} |\n`;

}

md += "\n";

md += "---\n\n";

md += "Generated by **SpringSentinel**.\n";

fs.writeFileSync("spring-sentinel-comment.md", md);

console.log("Comment generated.");
