name: Test Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Spring PetClinic
        uses: actions/checkout@v4
        with:
          repository: spring-petclinic/spring-petclinic-rest

      - name: Run SpringSentinel
        run: |
          mvn -B io.github.pagano-antonio:spring-sentinel-maven-plugin:audit
